version: '2'
services:
  smsmessageapi:
    build:
      context: ./back
      dockerfile: Dockerfile-Node
    command: "bash -c 'yarn && yarn db:migrate && yarn start > /tmp/server.log 2>&1 & yarn start:server > /tmp/localtunnel.log  2>&1 & echo 'teste' && tail -f /tmp/localtunnel.log /tmp/server.log'"
    volumes:
      - ./back:/project
    links:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - MESSAGE_API_MONGO_HOST=mongodb

  mongodb:
    image: mongo:3.4.7
    ports:
      - 27017:27017

  smsmessage-front:
    command: "bash -c 'yarn && yarn start'"
    build: ./front
    volumes:
      - ./front:/project
    environment:
      - HOST=0.0.0.0
      - port=8080
    ports:
      - 8080:8080
